-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.activation_by_staff
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employe_id integer NOT NULL,
    staff_id integer,
    verifyed boolean NOT NULL,
    verify_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_codes
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    code character varying(50) NOT NULL,
    verifayed boolean NOT NULL,
    verify_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates
(
    id integer NOT NULL,
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    nationalnumber character varying(11) NOT NULL,
    birthdate date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 82 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    candidate_id integer NOT NULL,
    github character varying(75),
    linkedin character varying(75),
    biography text,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL,
    companyname character varying(50) NOT NULL,
    website character varying(50) NOT NULL,
    phone_number character varying(20) NOT NULL,
    isactived boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.experiences
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    "position" character varying(50) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.images
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50),
    image_url character varying(100) NOT NULL,
    cv_id integer NOT NULL,
    image_id character varying(50),
    PRIMARY KEY (id)
);

CREATE TABLE public.job_ad_activation
(
    job_ad_id integer NOT NULL,
    staff_id integer,
    confirm boolean NOT NULL,
    confirm_date date,
    PRIMARY KEY (job_ad_id)
);

CREATE TABLE public.job_ads
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id integer NOT NULL,
    jobposition_id integer NOT NULL,
    description text NOT NULL,
    city_id integer NOT NULL,
    min_salary integer,
    max_salary integer,
    open_positions integer NOT NULL,
    last_date date NOT NULL,
    active boolean NOT NULL,
    create_date date NOT NULL,
    work_time_id integer NOT NULL,
    workplace_id integer NOT NULL,
    confirmed boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "position" character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.languages
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    name character varying(50) NOT NULL,
    level character varying(1) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.schools
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    name character varying(75) NOT NULL,
    department character varying(75) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.staff
(
    id integer NOT NULL,
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.technologies
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cv_id integer NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    mail_is_verify boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.work_time
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.workplace
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.activation_by_staff
    ADD FOREIGN KEY (employe_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.activation_by_staff
    ADD FOREIGN KEY (staff_id)
    REFERENCES public.staff (id)
    NOT VALID;


ALTER TABLE public.activation_codes
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.cv
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.experiences
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cv (id)
    NOT VALID;


ALTER TABLE public.images
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cv (id)
    NOT VALID;


ALTER TABLE public.job_ad_activation
    ADD FOREIGN KEY (job_ad_id)
    REFERENCES public.job_ads (id)
    NOT VALID;


ALTER TABLE public.job_ad_activation
    ADD FOREIGN KEY (staff_id)
    REFERENCES public.staff (id)
    NOT VALID;


ALTER TABLE public.job_ads
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.job_ads
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_ads
    ADD FOREIGN KEY (jobposition_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.job_ads
    ADD FOREIGN KEY (work_time_id)
    REFERENCES public.work_time (id)
    NOT VALID;


ALTER TABLE public.job_ads
    ADD FOREIGN KEY (workplace_id)
    REFERENCES public.workplace (id)
    NOT VALID;


ALTER TABLE public.languages
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cv (id)
    NOT VALID;


ALTER TABLE public.schools
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cv (id)
    NOT VALID;


ALTER TABLE public.staff
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.technologies
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cv (id)
    NOT VALID;

END;
